DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS BANKUSER;
DROP TABLE IF EXISTS TRANSFER;

CREATE TABLE IF NOT EXISTS BANKUSER
(
   ID             SERIAL PRIMARY KEY,
   USERNAME       CHAR(50) UNIQUE NOT NULL,
   PASSWORD       CHAR(60) NOT NULL,
   ROLE           CHAR(4) NOT NULL DEFAULT 'BaCl' 
);

ALTER TABLE IF EXISTS BANKUSER
    OWNER TO postgres;


CREATE TABLE IF NOT EXISTS CUSTOMER
(
   ID  SERIAL PRIMARY KEY,
   USERNAME       CHAR(50) UNIQUE,
   ADDRESS        CHAR(50),
   BANKUSERID     INT,
   CONSTRAINT FK_BANKUSER
      FOREIGN KEY(BANKUSERID)
        REFERENCES BANKUSER(ID)
          ON DELETE CASCADE
);

ALTER TABLE IF EXISTS CUSTOMER
    OWNER to postgres;

----------------------------------

CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID          SERIAL PRIMARY KEY,
    CUSTOMERID  INT,
    BALANCE     NUMERIC(10,2),
    IBAN        CHAR(30) UNIQUE,
    CURRENCY    CHAR(5),
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY(CUSTOMERID)
        REFERENCES CUSTOMER(ID)
          ON DELETE CASCADE
);


ALTER TABLE IF EXISTS ACCOUNT
    OWNER to postgres;
----------------------------------

CREATE TABLE IF NOT EXISTS TRANSACTION
(
   ID  SERIAL PRIMARY KEY,
   ACCOUNTID       INT,
   AMOUNT        NUMERIC(10,2),
   TRANTS        TIMESTAMPTZ,
   OPERATIONTYPE CHAR(10),
   ACCBALANCE    NUMERIC(10,2),
   CONSTRAINT FK_ACCOUNT
      FOREIGN KEY(ACCOUNTID)
        REFERENCES ACCOUNT(ID)
          ON DELETE CASCADE
);
ALTER TABLE IF EXISTS TRANSACTION
    OWNER to postgres;
----------------------------------

CREATE TABLE IF NOT EXISTS TRANSFER
(
   ID               SERIAL PRIMARY KEY,
   SOURCE_IBAN      CHAR(30),
   DESTINATION_IBAN CHAR(30),
   AMOUNT           NUMERIC(10,2),
   CREATED_AT       TIMESTAMPTZ,
   CURRENCY         CHAR(3),
   CONSTRAINT FK_SOURCE_IBAN
      FOREIGN KEY(SOURCE_IBAN)
        REFERENCES ACCOUNT(IBAN)
          ON DELETE CASCADE,
   CONSTRAINT FK_DESTINATION_IBAN
      FOREIGN KEY(DESTINATION_IBAN)
        REFERENCES ACCOUNT(IBAN)
          ON DELETE CASCADE
);
ALTER TABLE IF EXISTS TRANSFER
    OWNER to postgres;
----------------------------------

